### ISSUE TITLE
a tegi va li tegi

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [ShokhrukhTurgunov/Pixer#3]
![image](https://user-images.githubusercontent.com/79502241/115498978-fafb7400-a287-11eb-9d13-dab3cbed4456.png)
`ul` ning bolasi `a `bo'laolmaydi. rasmdagi holatni `li` uning ichida `a` ga o'zgartirish kerak

**Comment by ShokhrukhTurgunov** [comment]
to'g'rilandi
