### ISSUE TITLE
a ning atributlari

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [ShokhrukhTurgunov/Pixer#4]
![image](https://user-images.githubusercontent.com/79502241/115499196-73623500-a288-11eb-9e3a-366e9483f5ac.png)
`a` ning `type` atributi mavjud emas uni `button` ga o'zgartirish kerak yoki `href` atributni o'chrib tashlash kerak

**Comment by ShokhrukhTurgunov** [comment]
to'g'rilandi
