### ISSUE TITLE
Buyurtma berish bo'limi

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [ShokhrukhTurgunov/Pixer#5]
![image](https://user-images.githubusercontent.com/79502241/115500504-d48b0800-a28a-11eb-91b2-9293898be6c9.png)
htmldagi inputlar orasidagi `br` tegi shart emas.
![image](https://user-images.githubusercontent.com/79502241/115500719-4cf1c900-a28b-11eb-8710-642c0f15a6e6.png)
forma ichidagi link `button`ga o'zgatrilishi kerak

**Comment by ShokhrukhTurgunov** [comment]
to'g'rilandi
